#' Estimate Jaccard's similarity
#' This function estimates Jaccard's similarity between users' gene set and
#' database gene set.

#'@param
#' enrichr_data_frame The data frame generated by function  enrichr_df.

#'@return The input  data frame is added  with a new column with Jaccard
#' similarity estimate.


#'@example
#' js <- estimate_jaccard_similarity(enrichr_data_frame = enrichr_df)

#' @export
estimate_jaccard_similarity <- function(enrichr_data_frame){
  JS <- enrichr_data_frame %>%
    mutate(gene_list_length = as.numeric(str_split_fixed
    (Overlap, "/", 2)[, 1]), term_list_length = as.numeric(str_split_fixed
    (Overlap, "/", 2)[,2])) %>%
    mutate(Jaccard_similarity = (gene_list_length/term_list_length))
  return(JS)
}
